version: "3.9"

services:
  app:
    build: .
    container_name: lotus-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:password@db:5432/lotus_db
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: postgres:15
    container_name: lotus-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lotus_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: